server:
  build: .
  command: mix run --no-halt
  dockerfile: Dockerfile.dev
  links:
    - elasticsearch
  env_file:
    - .env
  working_dir: /app
  volumes:
    - .:/app
elasticsearch:
  image: elasticsearch:latest
  ports:
    - "9200"
