# Set the Docker image you want to base your image off.
# I chose this one because it has Elixir preinstalled.
FROM trenpixster/elixir:1.3.0

# Compile app
RUN mkdir /app
WORKDIR /app

# Install Elixir Deps
ADD mix.* ./
RUN mix local.hex --force
RUN mix local.rebar
RUN mix deps.get

# Install app
WORKDIR /app
ADD . /app
